### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Dandiasdd** [kekmodel/MPL-pytorch#14]
i encountered this error while running my code with GPU
```WARNING:__main__:Process rank: 0, device: cuda:0, distributed training: True, 16-bits training: True
2021-03-30 16:11:36.205545: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Killing subprocess 1237
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'drive/MyDrive/MPL/main.py', '--local_rank=0', '--name=hateful_memes_with_MPL', '--expand-labels', '--amp']' died with <Signals.SIGKILL: 9>.```

do you know the cause of this error ? thanks

**Comment by Dandiasdd** [comment]
``` asdasd ```

**Comment by kekmodel** [comment]
Please check the CUDA version.
